### ISSUE TITLE
ca_control_msgs.msg is unavailable

### ISSUE THREAD

**Issue by ggttkl** [hocherie/ecbf_quadrotor_ros#1]
Hi hocherie
I am very interested in your work about control barrier function. I tried to run your launch file to learn how cbf works but I cannot find ca_control_msgs.msg. Would you please give some hints to  install or find this package to finish the code? Thank you in advance!

**Comment by hocherie** [comment]
Hi, thanks for your interest. Unfortunately, that dependecy is for our lab's internal ROS use. 

Please check out our standalone Python implementation [here](https://github.com/hocherie/cbf_quadrotor)! There are some interactive exercises in [these slides](https://github.com/hocherie/cbf_quadrotor/blob/master/docs/ensuring-safety-pdf.pdf) (from slide 71) that you can play with.
